version: 2
updates:
  # Enable version updates for npm (main package)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "keep-starknet-strange/maintainers"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for React Native
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (docs)
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "keep-starknet-strange/maintainers"
    labels:
      - "dependencies"
      - "documentation"
      - "automated"
    commit-message:
      prefix: "chore(docs-deps)"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "keep-starknet-strange/maintainers"
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(actions)" 